### ISSUE TITLE
Improve chat list selection/view

### ISSUE THREAD

**Issue by smophat7** [beanlab/byoLAD#116]
Each conversation preview needs to be identifiable. Ideas:
- Last used date
- Name of code file
- Preview of first/last line messages
- Preview of code snippets

It can be pretty big. Clarity is important.

**Comment by EianWright** [comment]
Bumping this as a future improvement.

**Comment by smophat7** [comment]
Notes from 2024-03-04 class:
- Sort chat list by most recently modified? Requires adding a `date` property to a `ChatMessage` (probably in UTC and then display with `.toLocaleString()` stuff?) Also, display this date? Or created? Not sure what we said about this (if anything honestly)
  - If we add these, at least display the date of a message in the ChatView
- Increase size of the chat in the chatlist so there's more info available
  - First line: title, (date?), edit title/delete buttons
  - Next line(s): tags (`<VSCodeTag>`)
    - First tag: Persona (visually distinct somehow?)
    - Subsequent tags: Files referenced in chat (if any)
      - File tags require adding/populating a `fileName` or `filePath` (or something) property to `CodeBlock` that is set when the user adds it to the chat but probably just left null if the CodeBlock is created by parsing markdown (used in handling LLM responses and parsing user input)
- Not sure which part should be clickable to open that chat

Not sure how to prioritize this. Could probably do it in chunks and break this into multiple issues
