### ISSUE TITLE
Prompt engineering for code review

### ISSUE THREAD

**Issue by byubean** [beanlab/byoLAD#23]
Come up with an awesome "code review" prompt
Make sure only code is returned for all engines
Instructions to:
- fix bugs
- fix style
- performance improvements?
- security issues
- etc.

**Comment by m13467** [comment]
This is my current prompt it doesn't do everything at the moment, but it does a decent job. "Review the code and fix any bugs. See if there is a get and set function for each variable. Add documentation to the code, then return only code."

**Comment by m13467** [comment]
Actually, that one did not work as well in Python for me, so maybe just the plain "Review the code and fix any bugs. Add documentation to the code, then return only code."
