### ISSUE TITLE
Fundamental Fuctionality

### ISSUE THREAD

**Issue by m13467** [beanlab/byoLAD#4]
Thinking about the basic functionality that we want the extension to have, I came up with this list. Does the list seem like the basic functionality that we want for the extension? Or is there more that we would like to add? 

Code Review
   -Spell checking / Naming checking
   -Checking for Bugs
   -Cleaning up code
Complete Code/ Suggest a completion
Modify the Suggested Code

**Comment by EianWright** [comment]
That list seems complete to me. I'd like @brazilbean's input on it though.

**Comment by EianWright** [comment]
- Review code
- Explain code
- Custom prompt
- Sidebar interaction
